# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 860994b096d9e39902a50b0152855ce2cbe979e623f069dd7934889368b018cb1ac844545bedc571be19a49f10406fbe398a083c9f4bb1acbf23e1cc5bf3c0f4

test:
  secret_key_base: c34773da257ade40502d56a6d10a28d8566c8af6a5e3d675f9f52eadea485501903e6bd12689a4230b186d236444b79a540865231acb54874d9b2c5fffe04586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
