# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1428076177);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1428076297);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1428075937);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1428076057);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1428075817);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140715214327");
user_pref("browser.slowStartup.averageTime", 268906);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20140715214327");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1427957309633");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1428075762557");
user_pref("datareporting.policy.firstRunTime", "1427870909633");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.firstPaint", 7563);
user_pref("datareporting.sessions.current.main", 1446);
user_pref("datareporting.sessions.current.sessionRestored", 7846);
user_pref("datareporting.sessions.current.startTime", "1428082952601");
user_pref("datareporting.sessions.current.totalTime", 35);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1427870906073,\"a\":26,\"t\":181,\"c\":false,\"m\":1946,\"fp\":6884,\"sr\":8157}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1427878248097,\"a\":81,\"t\":2516,\"c\":true,\"m\":1656,\"fp\":7018,\"sr\":7567}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1427894593351,\"a\":36,\"t\":268,\"c\":false,\"m\":1437,\"fp\":7758,\"sr\":8934}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1428075694009,\"a\":77,\"t\":590,\"c\":false,\"m\":1226,\"fp\":7537,\"sr\":7862}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"31.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"31.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.09.20.beta,ubufox%40ubuntu.com:2.9,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150311.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1406067316000,\"rdfTime\":1390969548000}}},{\"name\":\"app-system-share\",\"addons\":{\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1406067315000,\"rdfTime\":1379719396000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1406067316000,\"rdfTime\":1397665356000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1406067315000,\"rdfTime\":1401829706000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1406067038000,\"rdfTime\":1405462641000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1405463749000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1405463749000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20140715214327");
user_pref("gecko.mstone", "31.0");
user_pref("idle.lastDailyNotification", 1428076335);
user_pref("lightweightThemes.isThemeSelected", true);
user_pref("lightweightThemes.persisted.footerURL", true);
user_pref("lightweightThemes.persisted.headerURL", true);
user_pref("lightweightThemes.usedThemes", "[{\"id\":\"597966\",\"name\":\"It's Spring Time!\",\"headerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/597966/header.png?1427329226\",\"footerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/597966/footer.png?1427329226\",\"textcolor\":\"#FFF5D9\",\"accentcolor\":\"#FFF5D9\",\"iconURL\":\"https://addons.cdn.mozilla.net/user-media/addons/597966/icon.png?1427329226\",\"previewURL\":\"https://addons.cdn.mozilla.net/user-media/addons/597966/preview.png?1427329226\",\"author\":\"ThemeHunter\",\"updateURL\":\"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/597966\",\"version\":\"0\",\"updateDate\":1428076178474,\"installDate\":1427894762829},{\"id\":\"184305\",\"name\":\"ANIMATED - Snoopy Nap\",\"headerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/184305/SnoopyNWoodstock.png?1277414453\",\"footerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/184305/SnoopyNapFooter.jpg?1277414453\",\"textcolor\":\"#fafaf7\",\"accentcolor\":\"#4bbac2\",\"iconURL\":\"https://addons.cdn.mozilla.net/user-media/addons/184305/preview_small.jpg?1277414453\",\"previewURL\":\"https://addons.cdn.mozilla.net/user-media/addons/184305/preview.jpg?1277414453\",\"author\":\"VanityFlair\",\"description\":\"( peanuts comic strip woodstock snoopy cartoon anime moving sleeping snoring blue green tree dog house red yellow bird sky grass sun summer cute )\",\"updateURL\":\"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/184305\",\"version\":\"1.0\",\"updateDate\":1427894862639,\"installDate\":1427894862639}]");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 102671);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1428082954);
user_pref("toolkit.telemetry.previousBuildID", "20140715214327");
